x-veld:
  code:
    description: "generic xml / xslt transformation setup."
    topics: 
      - "ETL"
      - "preprocessing"

    inputs:
      - volume: /veld/input/xml/
        environment: in_xml_file
        description: "the input xml file or folder containing xml"
        file_type: "xml"
        optional: true
      - volume: /veld/input/xsl/
        environment: in_xsl_file
        description: "the input xsl file or folder containing xsl"
        file_type: "xslt"
        optional: true

    outputs:
      - volume: /veld/output/
        environment: out_txt_file
        description: "output file or folder for converted txt"
        file_type: 
        - "xml"
        - "txt"

    settings:
      - environment: in_xml_url
        description: "a url pointing to an xml"
        env_type: "url"
        optional: true # though either in_xml_file or in_xml_url must be defined
      - environment: in_xsl_url
        description: "a url pointing to an xsl"
        env_type: "url"
        optional: true # though either in_xsl_file or in_xsl_url must be defined

services:
  veld:
    build: .
    command: /veld/code/transform.sh
    volumes:
      - ./src/:/veld/code/
    environment:
      in_xsl_file: null
      in_xml_file: null
      out_txt_file: null

