x-veld:
  code:
    description: "generic xml / xslt transformation setup."
    topic: 
      - "ETL"
      - "preprocessing"

    input:
      - volume: /veld/input/xml/
        environment_var: in_xml_file
        description: "the input xml file or folder containing xml. Note that if var `in_xml_file` 
          is set, this script will only transform that file. If it's not set, it will go through 
          the input folder recursively and create an equivalent output data structure."
        file_type: "xml"
        optional: true
      - volume: /veld/input/xsl/
        environment_var: in_xsl_file
        description: "the input xsl file or folder containing xsl"
        file_type: "xslt"
        optional: true

    output:
      - volume: /veld/output/
        environment_var: out_txt_file
        description: "output file or folder for converted txt. Note that the var 'out_txt_file' is 
          only respected, when the input is a single xml file. If the input is a folder, the output 
          will be an equivalent data structure and the var 'out_txt_file' is ignored."
        file_type: 
        - "xml"
        - "txt"

services:
  veld:
    build: .
    command: /veld/code/transform.sh
    volumes:
      - ./src/:/veld/code/
    environment:
      in_xsl_file: null
      in_xml_file: null
      out_txt_file: null

